# Site settings
title: Kónya Márton Blogja
description: > # this means to ignore newlines until "baseurl:"
  Privacy-vel és más egyéb számítógépes és internetes témákkal foglalkozó blog.
baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: # add disqus shortname here

# author info
# add your appropriate info here
author: Kónya Márton
bio:    Kónya Márton vagyok
email:
email_md5: # md5 hash of your email
twitter_username: Koma522
github_username:  Koma52

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
